# Generated by Django 6.0.1 on 2026-04-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_privatesession_active_connections_privatesession_all_left_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='sessions_ap_session_f6dc4b_idx',
            old_name='sessions_ap_chat_idx',
        ),
        migrations.RenameIndex(
            model_name='privatesession',
            new_name='sessions_ap_teacher_73c4a5_idx',
            old_name='sessions_ap_teacher_idx',
        ),
        migrations.RenameIndex(
            model_name='privatesession',
            new_name='sessions_ap_request_6d0b17_idx',
            old_name='sessions_ap_request_idx',
        ),
        migrations.RenameIndex(
            model_name='privatesession',
            new_name='sessions_ap_status_a89ba6_idx',
            old_name='sessions_ap_status_idx',
        ),
        migrations.RenameIndex(
            model_name='privatesession',
            new_name='sessions_ap_schedul_d86d00_idx',
            old_name='sessions_ap_date_idx',
        ),
    ]
